### ISSUE TITLE
Amplifier :: Prototype 2 :: General routing conventions to be followed

### ISSUE THREAD

**Issue by iqrohan** [iquesters/embedded#4]
1. All connectors to be on the edges of the boards.
2. All POTs to be placed at the edges of the board. Only the shaft will be hanging out. Refer M1 layout.
3. All 1/4" sockets to be placed at the edges of the board. Only the screw shaft will be hanging out. Refer M1 layout.
4. Names of 1/4: sockets to be displayed in the layout file. Change the library if necessary.
5. All vias must have drill = 0.8 mm and diameter = 1.5 mm
6. Jumper width = 0.8 mm. Jumpers can only be placed on voltage, ground and ground break lines. Try not to have jumpers on audio signal lines.
7. Component names: Font = vector, Size = 0.8 mm, Ratio = 15
8. Fill planes: Isolate = 0.5 mm

**Comment by iqsourav** [comment]
1. All connectors are on the edges of the boards.
2. All POTs are placed at the edges of the board. Only the shaft is hanging out.
3. All 1/4" sockets are placed at the edges of the board. Only the screw shaft is hanging out.
4. Names of 1/4 sockets are now visible in the layout file.
5. All vias have drill = 0.8 mm and diameter = 1.5 mm
6. Jumper width = 1.2 mm for Voltage ground and ground break lines. In some specific cases jumpers are in audio signal line.
7. Component names are fixed with Font = vector, Size = 0.8 mm, Ratio = 15
8. GND Fill Isolation = 0.5 mm Done.

Issue fixed ready for checking.
